nim = input("Nim: ")
nama = input("Nama Lengkap: ")
jurusan = input("Jurusan: ")
alamat = input("Alamat: ")

print("Hasil cetak diatas adalah")
print("Nim : " + str(nim))
print("Nama : " + str(nama))
print("Jurusan : " + str(jurusan))
print("Alamat : " + str(alamat))
